# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

#This pipeline uses an artifact feed for dotnet restore
- task: DotNetCoreCLI@2
  displayName: 'Artifact feed for dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'Allget' # A series of numbers and letters
  
#Create a NuGet package
- task: DotNetCoreCLI@2
  displayName: 'Create a NuGet package'
  inputs:
    command: pack
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(Patch)'
    packagesToPack: '**/*.csproj'

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  displayName: 'NuGet push to serverlesscompute/Allget'
  inputs:
    command: push
    publishVstsFeed: 'serverlesscompute/Allget'
    allowPackageConflicts: true
    




